apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: decomission-site
  name: decomission-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: decomission-site
  template:
    metadata:
      labels:
        app: decomission-site
    spec:
      containers:
        - name: decomission-site
          image: conreg.lanceolata.com.au/scouts-tasmania/aim/decomission-site/site:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: website
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 2
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 80
      imagePullSecrets:
        - name: conregkey
---
apiVersion: v1
kind: Service
metadata:
  name: decomission-site
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: decomission-site
  sessionAffinity: None
  type: ClusterIP