apiVersion: v1
kind: Service
metadata:
  name: wordpress-maria
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
  selector:
    app: wordpress-maria
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: wordpress-maria  # Sets Deployment name
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  replicas: 1
  serviceName: wordpress-maria
  selector:
    matchLabels:
      app: wordpress-maria
  template:
    metadata:
      labels:
        app: wordpress-maria
    spec:
      containers:
        - name: wordpress-maria
          image: mariadb:10.9.5
          imagePullPolicy: Always
          ports:
            - containerPort: 3306  # Exposes container port
          args: [
            "--character-set-server=utf8mb4", 
            "--collation-server=utf8mb4_unicode_ci", 
            "--skip-character-set-client-handshake", 
            "--skip-innodb-read-only-compressed"
          ]
          startupProbe:
            exec:
              command:
              - bash
              - -c
              - mysqladmin ping -h localhost --password=$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 10
            periodSeconds: 2
            failureThreshold: 5
          livenessProbe:
            exec:
              command:
              - bash
              - -c
              - mysqladmin ping -h localhost --password=$MYSQL_ROOT_PASSWORD
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 2
          env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: db-root-password
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mariadb-data
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: wordpress-maria-pv-claim
---

