apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erpnext-maria-pv-claim
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---