---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
  selector:
    app: wordpress
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
    app: wordpress
  name: wordpress
  annotations:
    argocd.argoproj.io/sync-wave: "30"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: website
              protocol: TCP
          readinessProbe:
            failureThreshold: 5
            initialDelaySeconds: 2
            periodSeconds: 2
            successThreshold: 1
            tcpSocket:
              port: 80
          volumeMounts:
            - mountPath: /var/www/html
              name: www-data
          env:
          - name: WORDPRESS_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-password
                key: db-root-password
          - name: WORDPRESS_DB_HOST
            value: "wordpress-maria"
          - name: WORDPRESS_DB_USER
            value: "root"
          - name: WORDPRESS_DB_NAME
            value: "wordpress"
      volumes:
        - name: www-data
          persistentVolumeClaim:
            claimName: wordpress-pv-claim